install.packages("devtools")
library(devtools)
install_github("slidify", "ramnathv")
install_github("slidifyLibraries", "ramnathv")
library(slidify)

getwd()
setwd("~")
setwd("~\\..\\Google Drive\\Data Science\\09_DevelopingDataProducts\\DDP_slide")
author("DDP project")
dir()

library(knitr)
slidify("index.Rmd")
browseURL("index.html")
